os: linux
language: generic

services:
  - docker

after_success:
  - docker build -t "filipdadgar/hb-store" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push "filipdadgar/hb-store"
  - echo "done pushing!"
