services:
  - docker

before_install:
  - docker build -t filipdadgar/hb-store .
  - docker run -d -p 8888:8888 -e host=localhost -e port=8888 filipdadgar/hb-store /bin/sh -c "/app/hb-store-cdn-cli-server-linux start"
  - docker ps -a
