os: linux
dist: trusty
language: generic

services:
  - docker

after_success:
  - docker build -t "filipdadgar/hb-store" .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "filipdadgar/hb-store"
  - echo "done pushing!"
