dist: trusty

services:
  - docker

after_success:
  - docker build -t "filipdadgar/hb-store" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "filipdadgar/hb-store"
